language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "10"
script: echo "No build stage"
deploy:
  provider: script
  # Note: change "docs" to the directory where your gatsby-site lives, if necessary
  script: yarn install && yarn run travis-deploy
  skip_cleanup: true
  on:
    branch: source
cache:
    yarn: true
    directories:
      - node_modules
